apiVersion: v1
kind: Pod
metadata:
  name: nginxpodlabel
  labels:
    app: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.16.0
    ports:
      - name: nginxport
        containerPort: 80
  nodeSelector:
    disktype: ssd        